### ISSUE TITLE
[SUGGESTION] Keybind toggle

### ISSUE THREAD

**Issue by srnyx** [colbiedison/unglow#3]
A keybind that can be set to toggle whether signs (that have glowing) will glow or not.
And maybe also a config option (via Mod Menu) to toggle.

**Comment by colbiedison** [comment]
I've added a keybind to toggle the mod (`g` by default). The toggle state is saved to a config file. See https://github.com/colbiedison/unglow/commit/8d0b128cf06a3a55c305173814b0d8288b3beb15
