### ISSUE TITLE
1.19, Modrinth, CurseForge

### ISSUE THREAD

**Issue by srnyx** [colbiedison/unglow#4]
1. Does it need to be updated to 1.19?
2. Can you upload it to [Modrinth](https://modrinth.com)
3. Can you upload it to [CurseForge](https://curseforge.com) (not really needed)

**Comment by colbiedison** [comment]
https://github.com/colbiedison/unglow/commit/9e89b6919fb9765675b5a2c47ec2b49ad3789a3e Updated to 1.19
I've submitted the mod to Modrinth and will close this issue when it is approved.

**Comment by colbiedison** [comment]
[That was fast.](https://modrinth.com/mod/unglow)
